#!/usr/bin/env python3

import argparse
import pathlib
import sys

from libwyag import Repository, BaseObject, Ref, Index


def cmd_init(args):
    Repository.create(args.path)


def cmd_catfile(args):
    obj = BaseObject.read(Repository.find(), args.object)
    sys.stdout.buffer.write(obj.serialize())


def cmd_hashobject(args):
    sha = BaseObject.create_from_file(
        Repository.find() if args.write else None,
        args.type,
        args.path,
        )
    print(sha)


def cmd_log(args):
    repo = Repository.find()

    def inner(commit, seen=[]):
        if commit.sha in seen:
            return
        seen.append(commit.sha)

        print(f"{commit.sha[:7]}: {commit.headline}")

        for p in commit.parents:
            inner(p, seen)

    inner(BaseObject.read(repo, args.commit))


def cmd_ls_tree(args):
    repo = Repository.find()

    obj = BaseObject.read(repo, args.object)
    if obj.fmt != "tree":
        raise Exception("ls-tree is only for tree object.")

    # TODO: git ls-tree shows the entries in current dir
    for e in obj.entries:
        print("%s %s %s\t%s" % (
            "0" * (6 - len(e.mode)) + e.mode,
            BaseObject.read(repo, e.sha).fmt,
            e.sha,
            e.path,
            ))


def cmd_checkout(args):
    repo = Repository.find()

    def inner(root, tree):
        for e in tree.entries:
            obj = BaseObject.read(repo, e.sha)
            path = root / e.path
            if obj.fmt == "tree":
                path.mkdir()
                inner(path, obj)
            elif obj.fmt == "blob":
                path.write_bytes(obj.serialize())

    root = pathlib.Path(args.path)
    if not root.exists():
        root.mkdir()
    if root.is_dir():
        if list(root.glob("*")):
            raise Exception("Not a empty directory: {root}")
        else:
            obj = BaseObject.read(repo, args.object)
            if obj.fmt == "tree":
                inner(root, obj)
            elif obj.fmt == "commit":
                inner(root, BaseObject.read(repo, obj.tree_sha))
    else:
        raise Exception("Not a directory (file exists): {root}")


def show_ref_inner(refs, prefix="", only_tags=False, show_path=True):
    for k, v in refs.items():
        child = (prefix + "/" if len(prefix) > 0 else "") + k
        if type(v) == str:
            if show_path:
                print("{v} {child}")
            else:
                print(k)
        else:
            show_ref_inner(v, child)


def cmd_show_ref(args):
    show_ref_inner(Ref.find_all(Repository.find()), prefix="refs")


def cmd_tag(args):
    repo = Repository.find()
    if args.name:
        if args.create_tag_object:
            Tag.create_object(repo, args.name, args.object)
        else:
            Tag.create_ref(repo, args.name, args.object)
    else:
        show_ref_inner(Ref.find_all(repo)["tags"], prefix="refs/tags", only_tags=True, show_path=False)


def cmd_rev_parse(args):
    print(Repository.find().object_find(args.name, fmt=args.type))


def cmd_cat_index(args):
    index = Index.read(Repository.find())

    print("Entries")
    for e in index.entries:
        print(e)
    print()

    if not index.tree is None:
        print("TREE")
        for e in index.tree:
            print(e)
        print()


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Write yourself a Git with Python")
    cmd_parser = parser.add_subparsers(title="Commands", dest="command", required=True)

    parser_init = cmd_parser.add_parser("init", help="Initialize a new, empty repository.")
    parser_init.add_argument("path", metavar="directory", nargs="?", default=".", help="Where to create the repository.")

    parser_catfile = cmd_parser.add_parser("cat-file", help="Provide content of repository objects.")
    parser_catfile.add_argument("type", metavar="type", choices=["blob", "commit", "tag", "tree"], help="Specify the type.")
    parser_catfile.add_argument("object", metavar="object", help="The object to display.")

    parser_hashobject = cmd_parser.add_parser("hash-object", help="Compute object ID and optionally creates a blob from a file")
    parser_hashobject.add_argument("-t", metavar="type", dest="type", choices=["blob", "commit", "tag", "tree"], default="blob", help="Specify the type.")
    parser_hashobject.add_argument("-w", dest="write", action="store_true", help="Actually write the object into the database.")
    parser_hashobject.add_argument("path", help="Read object from <file>.")

    parser_log = cmd_parser.add_parser("log", help="Display history of a given commit.")
    parser_log.add_argument("commit", default="HEAD", nargs="?", help="Commit to start at.")

    parser_ls_tree = cmd_parser.add_parser("ls-tree", help="Pretty-print a tree object.")
    parser_ls_tree.add_argument("object", help="The object to show.")

    parser_checkout = cmd_parser.add_parser("checkout", help="Checkout a commit inside of a directory.")
    parser_checkout.add_argument("object", help="The commit or tree to checkout.")
    parser_checkout.add_argument("path", help="The EMPTY directory to checkout on.")

    parser_show_ref = cmd_parser.add_parser("show-ref", help="List references.")

    parser_tag = cmd_parser.add_parser("tag", help="List and create tags.")
    parser_tag.add_argument("-a", dest="create_tag_object", action="store_true", help="Whether to create a tag object.")
    parser_tag.add_argument("name", nargs="?", help="The new tag's name.")
    parser_tag.add_argument("object", nargs="?", help="The object the new tag will point to.")

    parser_rev_parse = cmd_parser.add_parser("rev-parse", help="Parse revision (or other objects) identifiers.")
    parser_rev_parse.add_argument("--wyag-type", metavar="type", dest="type", choices=["blob", "commit", "tag", "tree"], default=None, help="Specify the expected type.")
    parser_rev_parse.add_argument("name", help="The name to parse.")

    parser_cat_index = cmd_parser.add_parser("cat-index", help="Show contents of .git/index.")

    args = parser.parse_args(sys.argv[1:])
    if   args.command == "init"        : cmd_init(args)
    elif args.command == "cat-file"    : cmd_catfile(args)
    elif args.command == "hash-object" : cmd_hashobject(args)
    elif args.command == "log"         : cmd_log(args)
    elif args.command == "ls-tree"     : cmd_ls_tree(args)
    elif args.command == "checkout"    : cmd_checkout(args)
    elif args.command == "show-ref"    : cmd_show_ref(args)
    elif args.command == "tag"         : cmd_tag(args)
    elif args.command == "rev-parse"   : cmd_rev_parse(args)
    elif args.command == "cat-index"   : cmd_cat_index(args)
